markpropertyset_spec =
[
	(:x, VegaValueRef, nothing),
	(:x2, VegaValueRef, nothing),
	(:xc, VegaValueRef, nothing),
	(:width, VegaValueRef, nothing),
	(:y, VegaValueRef, nothing),
	(:y2, VegaValueRef, nothing),
	(:yc, VegaValueRef, nothing),
	(:height, VegaValueRef, nothing),
	(:opacity, VegaValueRef, nothing),
	(:fill, VegaValueRef, nothing),
	(:fillOpacity, VegaValueRef, nothing),
	(:stroke, VegaValueRef, nothing),
	(:strokeWidth, VegaValueRef, nothing),
	(:strokeOpacity, VegaValueRef, nothing),
	(:strokeDash, VegaValueRef, nothing),
	(:strokeDashOffset, VegaValueRef, nothing),
	(:cursor, VegaValueRef, nothing),
	(:clip, VegaValueRef, nothing),
	(:size, VegaValueRef, nothing),
	(:shape, VegaValueRef, nothing),
	(:path, VegaValueRef, nothing),
	(:innerRadius, VegaValueRef, nothing),
	(:outerRadius, VegaValueRef, nothing),
	(:startAngle, VegaValueRef, nothing),
	(:endAngle, VegaValueRef, nothing),
	(:interpolate, VegaValueRef, nothing),
	(:tension, VegaValueRef, nothing),
	(:orient, VegaValueRef, nothing),
	(:url, VegaValueRef, nothing),
	(:align, VegaValueRef, nothing),
	(:baseline, VegaValueRef, nothing),
	(:text, VegaValueRef, nothing),
	(:dx, VegaValueRef, nothing),
	(:dy, VegaValueRef, nothing),
	(:radius, VegaValueRef, nothing),
	(:theta, VegaValueRef, nothing),
	(:angle, VegaValueRef, nothing),
	(:font, VegaValueRef, nothing),
	(:fontSize, VegaValueRef, nothing),
	(:fontWeight, VegaValueRef, nothing),
	(:fontStyle, VegaValueRef, nothing),
	# (:title, VegaValueRef, nothing),
	# (:labels, VegaValueRef, nothing),
	# (:legend, VegaValueRef, nothing),
	# (:symbols, VegaValueRef, nothing),
	# (:gradient, VegaValueRef, nothing)


]

primitivefactory(:VegaMarkPropertySet, markpropertyset_spec)
